# Generated by Django 4.2.7 on 2024-03-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_injury'),
    ]

    operations = [
        migrations.AddField(
            model_name='injury',
            name='scanning_report',
            field=models.FileField(blank=True, null=True, upload_to='scanning_reports/'),
        ),
    ]
