# Generated by Django 4.2.7 on 2024-04-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_scoutedplayer_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdetailsrequest',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
