# Generated by Django 4.2.7 on 2024-02-17 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('cdate', models.DateField(blank=True, null=True)),
                ('sal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('pos', models.CharField(blank=True, max_length=50, null=True)),
                ('jno', models.IntegerField(blank=True, null=True)),
                ('cdate', models.DateField(blank=True, null=True)),
                ('sal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('cdate', models.DateField(blank=True, null=True)),
                ('sal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('cdate', models.DateField(blank=True, null=True)),
                ('sal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cdate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='img',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='jno',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sal',
        ),
        migrations.RemoveField(
            model_name='match',
            name='time',
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.player'),
        ),
    ]
