# Generated by Django 4.2.7 on 2024-02-17 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_coach_player_scout_staff_remove_customuser_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.coach'),
        ),
    ]
