# Generated by Django 4.2.7 on 2024-02-20 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_coach_player_scout_staff_remove_customuser_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerDetailsRequest',
        ),
    ]
