# Generated by Django 4.2.7 on 2024-02-20 00:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_playerdetailsrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDetailsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('sal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('position', models.CharField(choices=[('CF', 'Forward'), ('CM', 'Midfielder'), ('CD', 'Defender'), ('GK', 'Goal Keeper')], max_length=50)),
                ('current_status', models.CharField(choices=[('Free', 'Free'), ('club', 'In a Club')], max_length=10)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('email', models.EmailField(max_length=254)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.scoutedplayer')),
            ],
        ),
    ]
