# Generated by Django 4.2.7 on 2024-02-19 08:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_coach_first_name_coach_last_name_player_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('position', models.CharField(choices=[('CF', 'Forward'), ('CM', 'Midfielder'), ('CD', 'Defender'), ('GK', 'Goal Keeper')], max_length=50)),
                ('current_status', models.CharField(choices=[('Free', 'Free'), ('club', 'In a Club')], max_length=10)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('email', models.EmailField(max_length=254)),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.scout')),
            ],
        ),
    ]
