# Generated by Django 4.2.5 on 2023-09-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('role', models.CharField(max_length=50)),
                ('jno', models.IntegerField(blank=True, null=True)),
                ('cdate', models.DateField(blank=True, null=True)),
                ('sal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('passwd', models.CharField(max_length=50)),
                ('img', models.ImageField(default='', upload_to='uploads')),
            ],
        ),
    ]
