# Generated by Django 4.2.6 on 2023-11-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_trainingsession_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsession',
            old_name='id',
            new_name='training_id',
        ),
    ]
